<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superglobais</title>
</head>

<body>

    <!-- 

    TIPOS DE SUPERGLOBAIS

    $_GET - PEGA OS DADOS QUE SAO ENVIADOS PELA URL E TAMBEM FICA VISIVEL LA

    $_POST - PEGA OS DADOS ENVIADOS PELO FORMULARIO, POREM, AINDA É POSSIVEL VER NAS CONFIGURAÇÕES DO NAVEGADOR

    $_REQUEST - PEGA OS VALORES DOS DOIS, INDEPENDENTE SE FOR GET OU POST

    $_COOKIE - ELE PEGA OS DADOS QUE FORAM ARMAZENADOS DENTRO DO NAVEGADOR DO USUARIO

    $_FILES - É USADO PARA RECEBER ARQUIVOS ENVIADOS PELO USUARIO(IMAGENS, PDF)

    $_SESSION - É USADA PARA GUARDAR DADOS DO USUARIO NO SERVIDOR ENQUANTO ELE NAVEGA NO SITE

    $_ENV - CONTEM AS VARIAVEIS DE AMBIENTE DO SERVIDOR, SAO COMO AS CONFIGURAÇÕES INTERNAS DO SISTEMA OPERACIONAL QUE O PHP VER

    $_SERVER - CONTEM AS INFORMAÇÕES SOBRE O SERVIDOR E SOBRE A REQUISIÇÃO ATUAL, É COMO UM PAINEL DE CONTROLE QUE MOSTRA OQ TA ACONTECENDO

    $GLOBALS - É A SUPERGLOBAL QUE CONTEM TODAS AS VARIAVEIS DO SISTEMA
     
    -->

    <pre>

        <?php

        setcookie("dia-da-semana", "SEGUNDA-FEIRA", time() + 3600); /* AQUI CRIAMOS UM COOKIE PARA FICAR ARMAZENADO TEMPORARIAMENTE NO NAVEGADOR, NO CASO O NOME DO COOKIE É 'dia-da-semana' E QUANDO CHAMARMOS ELE RETORNA O VALOR QUE ATRIBUIMOS 'SEGUNDA-FEIRA' */

        echo "<h1>SUPERGLOBAL COOKIE</h1>";

        var_dump($_COOKIE);

        echo "<br>";

        session_start();

        $_SESSION["TESTE"] = "FUNCIONOU";

        echo "<br><br><h1>SUPERGLOBAL SESSION<br></h1>";

        var_dump($_SESSION);

        echo "SUPERGLOBAL SERVER";

        var_dump($_SERVER);

        echo "<h1>SUPERGLOBAL GLOBALS</h1>";

        var_dump($GLOBALS); /* AQUI ELA ARMAZENA TODAS AS VARIAVEIS DAS OUTRAS SUPERGLOBAIS */

        ?>

    </pre>

</body>

</html>